ext {
  androidxAppCompatVersion = project.hasProperty('androidxAppCompatVersion') ? rootProject.ext.androidxAppCompatVersion : '1.7.0'
}
buildscript {
  repositories { google(); mavenCentral() }
  dependencies { classpath 'com.android.tools.build:gradle:8.2.1' }
}
apply plugin: 'com.android.library'
android {
  namespace "hu.zoll86.mappa"
  compileSdk project.hasProperty('compileSdkVersion') ? rootProject.ext.compileSdkVersion : 34
  defaultConfig {
    minSdkVersion project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 22
    targetSdkVersion project.hasProperty('targetSdkVersion') ? rootProject.ext.targetSdkVersion : 34
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
}
repositories { google(); mavenCentral() }
dependencies {
  implementation project(':capacitor-android')
  implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
  implementation "androidx.documentfile:documentfile:1.0.1"
}
